# Generated by Django 5.0 on 2023-12-23 02:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_string', models.CharField(choices=[('Weight Lifting', 'Weight Lifting'), ('Yoga', 'Yoga'), ('Bike Ride', 'Bike Ride'), ('Run', 'Run'), ('Walk', 'Walk'), ('Hiit', 'Hiit')], default='Weight Lifting', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_of_day', models.TimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('mood_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.CharField(max_length=100)),
                ('distance_miles', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weather_conditions', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiitPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_string', models.CharField(choices=[('Weight Lifting', 'Weight Lifting'), ('Yoga', 'Yoga'), ('Bike Ride', 'Bike Ride'), ('Run', 'Run'), ('Walk', 'Walk'), ('Hiit', 'Hiit')], default='Weight Lifting', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_of_day', models.TimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('mood_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.CharField(max_length=100)),
                ('exercise_label', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiftPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_string', models.CharField(choices=[('Weight Lifting', 'Weight Lifting'), ('Yoga', 'Yoga'), ('Bike Ride', 'Bike Ride'), ('Run', 'Run'), ('Walk', 'Walk'), ('Hiit', 'Hiit')], default='Weight Lifting', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_of_day', models.TimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('mood_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.CharField(max_length=100)),
                ('body_part', models.CharField(choices=[('Chest + Back', 'Chest + Back'), ('Legs', 'Legs'), ('Shoulders + Biceps', 'Shoulders + Biceps'), ('Shoulders + Triceps', 'Shoulders + Triceps'), ('Cardio + Biceps', 'Cardio + Biceps'), ('Cardio + Triceps', 'Cardio + Triceps'), ('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Cardio', 'Cardio'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps')], max_length=20)),
                ('includes_abs', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunningPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_string', models.CharField(choices=[('Weight Lifting', 'Weight Lifting'), ('Yoga', 'Yoga'), ('Bike Ride', 'Bike Ride'), ('Run', 'Run'), ('Walk', 'Walk'), ('Hiit', 'Hiit')], default='Weight Lifting', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_of_day', models.TimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('mood_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.CharField(max_length=100)),
                ('distance_miles', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weather_conditions', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalkingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_string', models.CharField(choices=[('Weight Lifting', 'Weight Lifting'), ('Yoga', 'Yoga'), ('Bike Ride', 'Bike Ride'), ('Run', 'Run'), ('Walk', 'Walk'), ('Hiit', 'Hiit')], default='Weight Lifting', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_of_day', models.TimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('mood_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.CharField(max_length=100)),
                ('distance_miles', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weather_conditions', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YogaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_string', models.CharField(choices=[('Weight Lifting', 'Weight Lifting'), ('Yoga', 'Yoga'), ('Bike Ride', 'Bike Ride'), ('Run', 'Run'), ('Walk', 'Walk'), ('Hiit', 'Hiit')], default='Weight Lifting', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_of_day', models.TimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('mood_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.CharField(max_length=100)),
                ('yoga_type', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiftPostSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=200)),
                ('reps', models.PositiveBigIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_posts.liftpost')),
            ],
        ),
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='workout_posts.yogapost')),
            ],
        ),
    ]
